// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SOC_IR.Data;

namespace SOC_IR.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210113052444_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("SOC_IR.Model.Admin", b =>
                {
                    b.Property<string>("nusNetId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("nusNetId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SOC_IR.Model.Announcement", b =>
                {
                    b.Property<string>("announceId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("announcedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("isActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("isImportant")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("lastUpdated")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("subtitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("validTill")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("announceId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("SOC_IR.Model.Company", b =>
                {
                    b.Property<string>("companyId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("companyDescription")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyTier")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("companyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SOC_IR.Model.CompanyPost", b =>
                {
                    b.Property<string>("companyPostId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("approvedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("isActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("lastUpdated")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("links")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postDescription")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postSubTitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postTitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("validTill")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("videoUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("companyPostId");

                    b.ToTable("CompanyPosts");
                });

            modelBuilder.Entity("SOC_IR.Model.CompanyPostRequest", b =>
                {
                    b.Property<string>("companyPostRequestId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("companyId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("feedback")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("links")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postDescription")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postSubTitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("postTitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("validTill")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("videoUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("companyPostRequestId");

                    b.ToTable("CompanyPostRequests");
                });

            modelBuilder.Entity("SOC_IR.Model.CompanyUser", b =>
                {
                    b.Property<string>("companyUserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("companyId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("companyName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("lastLoggedIn")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("companyUserId");

                    b.ToTable("CompanyUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
